const types={
  GET_TWEETS_START:'GET_TWEETS_START',
  GET_TWEETS_SUCCESS:'GET_TWEETS_SUCCESS',
  GET_TWEETS_FAILURE:'GET_TWEETS_FAILURE',
  ADD_TWEET_START:'ADD_TWEET_START',
  ADD_TWEET_SUCCESS:'ADD_TWEET_SUCCESS',
  ADD_TWEET_FAILURE:'ADD_TWEET_FAILURE',
}

export default types