const types={
  GET_TWEETS_START:'GET_USERS_START',
  GET_USERS_SUCCESS:'GET_USERS_SUCCESS',
  GET_USERS_FAILURE:'GET_USERS_FAILURE',
  ADD_USER_START:'ADD_USER_START',
  ADD_USER_SUCCESS:'ADD_USER_SUCCESS',
  ADD_USER_FAILURE:'ADD_USER_FAILURE',
}

export default types